name: Release
on:
  push:
    tags:
      - v*.*.*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
      - run: npm add -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck
      - run: pnpm run build
      - run: echo "# $(date +%F)"    >> ${{ github.workspace }}-CHANGELOG.txt
      - run: echo '```'              >> ${{ github.workspace }}-CHANGELOG.txt
      - run: cat out/bookmarklet.txt >> ${{ github.workspace }}-CHANGELOG.txt
      - run: echo '```'              >> ${{ github.workspace }}-CHANGELOG.txt
      - uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: out/*.*
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
